<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-FQJ2DVAE" ignored="0" name="COS14_PurchaseOrder(failed)(failed)" tests="2" failures="1" timestamp="26 Sep 2020 08:06:30 GMT" time="64.833" errors="0">
  <testcase name="PurchaseOrder" time="51.596" classname="com.cosacs.TestCases.COS14_PurchaseOrder">
    <failure type="java.lang.AssertionError" message="expected [  Purchase order saved successfully ] but found [Purchase order saved successfully]">
      <![CDATA[java.lang.AssertionError: expected [  Purchase order saved successfully ] but found [Purchase order saved successfully]
at com.cosacs.TestCases.COS14_PurchaseOrder.PurchaseOrder(COS14_PurchaseOrder.java:94)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- PurchaseOrder -->
  <testcase name="PurchaseOrderSearch" time="0.0" classname="com.cosacs.TestCases.COS14_PurchaseOrder">
    <skipped/>
  </testcase> <!-- PurchaseOrderSearch -->
</testsuite> <!-- COS14_PurchaseOrder(failed)(failed) -->
